import "./globals.css";
import AppProvider from "./_components/AppProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  console.log("root layout");
  // const cookieStore = await cookies();
  return (
    <html lang="en">
      <body>
        <main className="max-w-2/3 mx-auto px-3">
          <AppProvider>{children}</AppProvider>
        </main>
      </body>
    </html>
  );
}

//Làm sao vừa được dùng context để share tới tất cả client component
//Vẫn giữ được các page là server

//Lưu ý: Không lấy cookie, headers ở layout --> Tự động chuyển cả app thành Dynamic Rendering
