import Nav from "./_components/Nav";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main className="max-w-300 mx-auto">{children}</main>
      </body>
    </html>
  );
}
